# -*- coding: utf-8 -*-
"""supercashiermain

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXeV01kkOV1FNnUDlFW5vBhiv6MzbnoZ
"""

from transaction import Transaction

def main():
    print("Selamat datang di Home Market.")
    transaction = Transaction()
    transaction.show_menu()

if __name__ == "__main__":
    main()